# Generated by Django 5.2.7 on 2025-10-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contacts',
                to='customers.company',
                verbose_name='Компания',
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contacts',
                to='customers.customer',
                verbose_name='Клиент',
            ),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='customers',
                to='customers.company',
                verbose_name='Компания',
            ),
        ),
        migrations.AlterField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='customers',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Ответственный менеджер',
            ),
        ),
    ]
