module.exports = {
  customSyntax: 'postcss-sass',
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order'],
  rules: {
    'color-hex-length': 'short',
    'no-empty-source': null,
    'selector-class-pattern': null,
    'order/properties-order': [
      'display',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'flex',
      'flex-direction',
      'align-items',
      'justify-content',
      'width',
      'height',
      'margin',
      'padding',
      'font',
      'font-size',
      'font-weight',
      'color',
      'background',
      'border',
      'border-radius',
      'box-shadow',
      'transition',
    ],
  },
};
