# Generated by Django 5.2.7 on 2025-10-08 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
                ),
                (
                    'modified',
                    models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('guest', 'Гость'),
                            ('customer', 'Клиент'),
                            ('b2b', 'B2B Клиент'),
                            ('sales_manager', 'Менеджер продаж'),
                            ('warehouse', 'Склад'),
                            ('accountant', 'Бухгалтерия'),
                            ('content_manager', 'Контент-менеджер'),
                            ('admin', 'Администратор'),
                            ('driver', 'Водитель'),
                            ('loader', 'Грузчик'),
                        ],
                        default='sales_manager',
                        max_length=32,
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'core_userprofile',
                'ordering': ['-created'],
            },
        ),
    ]
