# Generated by Django 5.2.7 on 2025-10-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_sync_orders_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('guest', 'Гость'),
                    ('customer', 'Клиент'),
                    ('b2b', 'B2B Клиент'),
                    ('sales_manager', 'Менеджер продаж'),
                    ('warehouse', 'Склад'),
                    ('accountant', 'Бухгалтерия'),
                    ('content_manager', 'Контент-менеджер'),
                    ('admin', 'Администратор'),
                    ('driver', 'Водитель'),
                    ('loader', 'Грузчик'),
                ],
                default='sales_manager',
                max_length=32,
                verbose_name='Роль',
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
