# Generated by Django 5.2.7 on 2025-10-28 18:00

import pathlib

import django.core.files.storage
from django.db import migrations, models

import applications.core.models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url='/media/products/', location=pathlib.PurePosixPath('/media/products')
                ),
                upload_to=applications.core.models.PathAndRename(''),
                verbose_name='Файл',
            ),
        ),
    ]
