# Generated by Django 5.2.7 on 2025-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stocktransaction_affects_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='setup_install_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Монтаж, мин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='setup_uninstall_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Демонтаж, мин'),
        ),
    ]
