# Generated by Django 5.2.7 on 2025-10-28 17:18

import applications.core.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_installerqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/products/', location=pathlib.PureWindowsPath('C:/Users/gusit/Desktop/work/kudos-deploy-test/kudos-testing/media/products')), upload_to=applications.core.models.PathAndRename(''), verbose_name='Файл'),
        ),
    ]
