# Generated by Django 5.2.7 on 2025-11-05 09:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_available_stock_qty_product_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available_stock_qty",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Доступный остаток на складе",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Остаток на складе",
            ),
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity_delta",
                    models.IntegerField(
                        help_text="Положительное значение увеличивает склад, отрицательное уменьшает.",
                        verbose_name="Изменение количества",
                    ),
                ),
                (
                    "affects_available",
                    models.BooleanField(
                        default=True,
                        help_text="Если включено, доступный остаток изменится вместе с реальным.",
                        verbose_name="Влияет на доступный остаток",
                    ),
                ),
                (
                    "is_applied",
                    models.BooleanField(
                        default=True,
                        help_text="Неприменённые транзакции используются для планирования и не влияют на остатки.",
                        verbose_name="Транзакция применена",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Запланировано на"
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Складская транзакция",
                "verbose_name_plural": "Складские транзакции",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
    ]
