# Generated by Django 5.2.7 on 2025-10-30 11:00

import applications.core.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_transportrestriction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='occupancy_insurance_reserve_percent',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/products/', location=pathlib.PureWindowsPath('C:/Users/gusit/Desktop/work/kudos-testing/media/products')), upload_to=applications.core.models.PathAndRename(''), verbose_name='Файл'),
        ),
    ]
