# Generated by Django 5.2.7 on 2025-10-10 15:33

from django.db import migrations, models


ROLE_FORWARD_MAP = {
    'client': 'customer',
    'manager': 'sales_manager',
    'administrator': 'admin',
}

ROLE_BACKWARD_MAP = {v: k for k, v in ROLE_FORWARD_MAP.items()}


def migrate_role_values_forward(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    for old_value, new_value in ROLE_FORWARD_MAP.items():
        UserProfile.objects.filter(role=old_value).update(role=new_value)


def migrate_role_values_backward(apps, schema_editor):
    UserProfile = apps.get_model('core', 'UserProfile')
    for new_value, old_value in ROLE_BACKWARD_MAP.items():
        UserProfile.objects.filter(role=new_value).update(role=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_role_values_forward, migrate_role_values_backward),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('customer', 'Клиент'), ('b2b', 'B2B Клиент'), ('sales_manager', 'Менеджер продаж'), ('warehouse', 'Склад'), ('accountant', 'Бухгалтерия'), ('content_manager', 'Контент-менеджер'), ('admin', 'Администратор'), ('driver', 'Водитель'), ('loader', 'Грузчик')], default='sales_manager', max_length=32),
        ),
    ]
