# Generated by Django 5.2.7 on 2025-10-30 17:15

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('new', 'Новый'),
                            ('reserved', 'В резерве'),
                            ('rented', 'В аренде'),
                            ('in_work', 'В работе'),
                            ('archived', 'Архив'),
                            ('declined', 'Отказ'),
                        ],
                        default='new',
                        max_length=32,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'total_amount',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=12,
                        verbose_name='Сумма заказа',
                    ),
                ),
                ('installation_date', models.DateField(verbose_name='Дата монтажа')),
                ('dismantle_date', models.DateField(verbose_name='Дата демонтажа')),
                (
                    'delivery_type',
                    models.CharField(
                        choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')],
                        default='delivery',
                        max_length=32,
                        verbose_name='Тип доставки',
                    ),
                ),
                (
                    'delivery_address',
                    models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки'),
                ),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                (
                    'customer',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='orders',
                        to='customers.customer',
                        verbose_name='Клиент',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                (
                    'product_name',
                    models.CharField(blank=True, max_length=255, verbose_name='Название товара'),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='Количество',
                    ),
                ),
                (
                    'unit_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='Цена за единицу',
                    ),
                ),
                (
                    'rental_days',
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name='Дней аренды',
                    ),
                ),
                (
                    'rental_mode',
                    models.CharField(
                        choices=[('standard', 'Стандартный'), ('special', 'Особый')],
                        default='standard',
                        max_length=32,
                        verbose_name='Режим аренды',
                    ),
                ),
                (
                    'rental_tiers_snapshot',
                    models.JSONField(
                        blank=True, default=list, verbose_name='Снимок тарифов аренды'
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='orders.order',
                        verbose_name='Заказ',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='order_items',
                        to='products.product',
                        verbose_name='Товар',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
