# Generated by Django 5.2.7 on 2025-11-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0002_order_services_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDriver',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО водителя')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                (
                    'phone_normalized',
                    models.CharField(
                        blank=True, max_length=32, verbose_name='Телефон (нормализованный)'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Водитель заказа',
                'verbose_name_plural': 'Водители заказов',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_full',
            field=models.CharField(
                blank=True, max_length=512, verbose_name='Адрес доставки (нормализованный)'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_input',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Адрес доставки (ввод)'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_kind',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тип объекта (kind)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address_precision',
            field=models.CharField(blank=True, max_length=32, verbose_name='Точность (precision)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lon',
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='dismount_datetime_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала демонтажа'),
        ),
        migrations.AddField(
            model_name='order',
            name='dismount_datetime_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания демонтажа'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_state',
            field=models.CharField(
                blank=True,
                choices=[
                    ('handover_to_picking', 'Передан на сборку'),
                    ('picked', 'Собран'),
                    ('shipped', 'Отгружен'),
                ],
                max_length=32,
                null=True,
                verbose_name='Состояние логистики',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='mount_datetime_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала монтажа'),
        ),
        migrations.AddField(
            model_name='order',
            name='mount_datetime_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания монтажа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('paid', 'Оплачен'),
                    ('unpaid', 'Не оплачен'),
                    ('partially_paid', 'Частично оплачен'),
                ],
                default='unpaid',
                max_length=32,
                verbose_name='Статус оплаты',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Принят на склад в'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_received_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='received_orders',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Принят на складе пользователем',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='yandex_uri',
            field=models.CharField(blank=True, max_length=255, verbose_name='URI в Яндекс'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['logistics_state'], name='orders_orde_logisti_b8a011_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipment_date'], name='orders_orde_shipmen_e91577_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['logistics_state', 'warehouse_received_at'],
                name='orders_orde_logisti_790737_idx',
            ),
        ),
        migrations.AddField(
            model_name='orderdriver',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='driver',
                to='orders.order',
                verbose_name='Заказ',
            ),
        ),
    ]
