# Generated by Django 5.2.7 on 2025-10-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_role_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
