# Generated by Django 5.0.7 on 2025-10-02 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('guest', 'Гость'),
                            ('client', 'Клиент'),
                            ('b2b', 'B2B Клиент'),
                            ('manager', 'Менеджер'),
                            ('warehouse', 'Склад'),
                            ('accountant', 'Бухгалтерия'),
                            ('content_manager', 'Контент-менеджер'),
                            ('administrator', 'Администратор'),
                        ],
                        default='manager',
                        max_length=32,
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
